name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -r requirements.dev
      - name: Apply ISORT to project
        run: |
          # 
          isort ./src/*.py -c -v
      - name: Apply Black to project
        run: |
          # 
          black ./src/*.py
              
      - name: Test with pytest
        run: |
          pytest
